<a href="https://www.kaggle.com/code/mdraisulislamkhan/mlb-02-assignment-3-by-md-raisul-islam-khan?scriptVersionId=347545650" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [29]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub

# Download latest version
path = kagglehub.dataset_download("saurabhbadole/restaurant-tips-dataset")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset


# import libraries

In [31]:
import numpy as np
import pandas as pd

In [37]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [35]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [38]:
# 1D, 2D, 3D and 4D arrays using np.array()
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]])

print("1D:\n", arr_1d)
print("2D:\n", arr_2d)
print("3D:\n", arr_3d)
print("4D:\n", arr_4d)


1D:
 [1 2 3 4 5]
2D:
 [[1 2 3]
 [4 5 6]]
3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4D:
 [[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]


# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [40]:
# 1D, 2D, 3D and 4D arrays using arange() and reshape()
arange_1d = np.arange(1, 7)
arange_2d = np.arange(1, 7).reshape(2, 3)
arange_3d = np.arange(1, 9).reshape(2, 2, 2)
arange_4d = np.arange(1, 17).reshape(2, 2, 2, 2)

print("1D:\n", arange_1d)
print("2D:\n", arange_2d)
print("3D:\n", arange_3d)
print("4D:\n", arange_4d)


1D:
 [1 2 3 4 5 6]
2D:
 [[1 2 3]
 [4 5 6]]
3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4D:
 [[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


# create array using ones and zeros

In [5]:
# arrays using ones() and zeros()
ones_1d = np.ones(5)
ones_2d = np.ones((2, 3))
zeros_1d = np.zeros(5)
zeros_2d = np.zeros((2, 3))

print("Ones 1D:", ones_1d)
print("Ones 2D:\n", ones_2d)
print("Zeros 1D:", zeros_1d)
print("Zeros 2D:\n", zeros_2d)


Ones 1D: [1. 1. 1. 1. 1.]
Ones 2D:
 [[1. 1. 1.]
 [1. 1. 1.]]
Zeros 1D: [0. 0. 0. 0. 0.]
Zeros 2D:
 [[0. 0. 0.]
 [0. 0. 0.]]


# using random

In [7]:
# arrays using random
random_1d = np.random.rand(5)
random_2d = np.random.randint(1, 10, size=(3, 3))

print("Random float array:\n", random_1d)
print("Random integer array:\n", random_2d)


Random float array:
 [0.97745913 0.35377607 0.02685401 0.88954268 0.04184971]
Random integer array:
 [[8 5 2]
 [4 9 5]
 [8 7 1]]


# using linspace

In [8]:
# using linspace
linear_array = np.linspace(0, 10, 6)
print(linear_array)


[ 0.  2.  4.  6.  8. 10.]


# create 1D array of tip from tips dataframe

In [41]:
# create 1D array of tip from tips dataframe
tip_array = tips["tip"].to_numpy()
print(tip_array)


[ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2.    2.    3.    3.48  

# create 2D array of tip and total_bill form tips dataframe

In [42]:
# create 2D array of tip and total_bill from tips dataframe
tip_bill_array = tips[["tip", "total_bill"]].to_numpy()
print(tip_bill_array)


[[ 1.01 16.99]
 [ 1.66 10.34]
 [ 3.5  21.01]
 [ 3.31 23.68]
 [ 3.61 24.59]
 [ 4.71 25.29]
 [ 2.    8.77]
 [ 3.12 26.88]
 [ 1.96 15.04]
 [ 3.23 14.78]
 [ 1.71 10.27]
 [ 5.   35.26]
 [ 1.57 15.42]
 [ 3.   18.43]
 [ 3.02 14.83]
 [ 3.92 21.58]
 [ 1.67 10.33]
 [ 3.71 16.29]
 [ 3.5  16.97]
 [ 3.35 20.65]
 [ 4.08 17.92]
 [ 2.75 20.29]
 [ 2.23 15.77]
 [ 7.58 39.42]
 [ 3.18 19.82]
 [ 2.34 17.81]
 [ 2.   13.37]
 [ 2.   12.69]
 [ 4.3  21.7 ]
 [ 3.   19.65]
 [ 1.45  9.55]
 [ 2.5  18.35]
 [ 3.   15.06]
 [ 2.45 20.69]
 [ 3.27 17.78]
 [ 3.6  24.06]
 [ 2.   16.31]
 [ 3.07 16.93]
 [ 2.31 18.69]
 [ 5.   31.27]
 [ 2.24 16.04]
 [ 2.54 17.46]
 [ 3.06 13.94]
 [ 1.32  9.68]
 [ 5.6  30.4 ]
 [ 3.   18.29]
 [ 5.   22.23]
 [ 6.   32.4 ]
 [ 2.05 28.55]
 [ 3.   18.04]
 [ 2.5  12.54]
 [ 2.6  10.29]
 [ 5.2  34.81]
 [ 1.56  9.94]
 [ 4.34 25.56]
 [ 3.51 19.49]
 [ 3.   38.01]
 [ 1.5  26.41]
 [ 1.76 11.24]
 [ 6.73 48.27]
 [ 3.21 20.29]
 [ 2.   13.81]
 [ 1.98 11.02]
 [ 3.76 18.29]
 [ 2.64 17.59]
 [ 3.15 20.08]
 [ 2.47 16

# practice atleast 2 example for each using ndim, shape, size and itemsize

In [43]:
# ndim: number of dimensions (2 examples)
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
print("ndim example 1:", a.ndim)
print("ndim example 2:", b.ndim)

# shape: size along each dimension (2 examples)
c = np.arange(6).reshape(2, 3)
d2 = np.arange(24).reshape(2, 3, 4)
print("shape example 1:", c.shape)
print("shape example 2:", d2.shape)

# size: total number of elements (2 examples)
e2 = np.array([[1, 2], [3, 4]])
f2 = np.arange(12).reshape(3, 4)
print("size example 1:", e2.size)
print("size example 2:", f2.size)

# itemsize: bytes used by one element (2 examples)
g = np.array([1, 2, 3], dtype=np.int32)
h = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print("itemsize example 1:", g.itemsize, "bytes")
print("itemsize example 2:", h.itemsize, "bytes")


ndim example 1: 1
ndim example 2: 2
shape example 1: (2, 3)
shape example 2: (2, 3, 4)
size example 1: 4
size example 2: 12
itemsize example 1: 4 bytes
itemsize example 2: 8 bytes


# change data type and memory size of any np-array using astype()

In [44]:
# change data type and memory size using astype()
original = np.array([1, 2, 3, 4, 5], dtype=np.int64)
converted = original.astype(np.int32)

print("Original:", original)
print("Original dtype:", original.dtype, "| itemsize:", original.itemsize, "bytes")
print("Converted:", converted)
print("Converted dtype:", converted.dtype, "| itemsize:", converted.itemsize, "bytes")


Original: [1 2 3 4 5]
Original dtype: int64 | itemsize: 8 bytes
Converted: [1 2 3 4 5]
Converted dtype: int32 | itemsize: 4 bytes


# create 2 same dimensional array and do scalar and vector operations

In [45]:
# create 2 same-dimensional arrays and perform scalar and vector operations
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[10, 20, 30], [40, 50, 60]])

print("Scalar addition (x + 5):\n", x + 5)
print("Scalar multiplication (x * 2):\n", x * 2)

print("Vector addition (x + y):\n", x + y)
print("Vector subtraction (y - x):\n", y - x)
print("Vector multiplication (x * y):\n", x * y)


Scalar addition (x + 5):
 [[ 6  7  8]
 [ 9 10 11]]
Scalar multiplication (x * 2):
 [[ 2  4  6]
 [ 8 10 12]]
Vector addition (x + y):
 [[11 22 33]
 [44 55 66]]
Vector subtraction (y - x):
 [[ 9 18 27]
 [36 45 54]]
Vector multiplication (x * y):
 [[ 10  40  90]
 [160 250 360]]


# find minimun and maximum tip

In [46]:
# find minimum and maximum tip
print("Minimum tip:", np.min(tip_array))
print("Maximum tip:", np.max(tip_array))


Minimum tip: 1.0
Maximum tip: 10.0


# find average total_bill and average tip

In [47]:
# find average total_bill and average tip
print("Average total_bill:", tips["total_bill"].to_numpy().mean())
print("Average tip:", tip_array.mean())


Average total_bill: 19.78594262295082
Average tip: 2.99827868852459


# find median total_bill

In [48]:
# find median total_bill
total_bill_array = tips["total_bill"].to_numpy()
print("Median total_bill:", np.median(total_bill_array))


Median total_bill: 17.795


# find standard deviasion and variance of tip

In [49]:
# find standard deviation and variance of tip
print("Standard deviation of tip:", np.std(tip_array))
print("Variance of tip:", np.var(tip_array))


Standard deviation of tip: 1.3807999538298954
Variance of tip: 1.9066085124966412


# find log values of tip

In [50]:
# find log values of tip
log_tip = np.log(tip_array)
print(log_tip)


[0.00995033 0.5068176  1.25276297 1.19694819 1.28370777 1.54968791
 0.69314718 1.137833   0.67294447 1.17248214 0.53649337 1.60943791
 0.45107562 1.09861229 1.10525683 1.36609165 0.51282363 1.31103188
 1.25276297 1.20896035 1.40609699 1.01160091 0.80200159 2.0255132
 1.1568812  0.85015093 0.69314718 0.69314718 1.45861502 1.09861229
 0.37156356 0.91629073 1.09861229 0.89608802 1.18478998 1.28093385
 0.69314718 1.12167756 0.83724752 1.60943791 0.80647587 0.93216408
 1.11841492 0.27763174 1.7227666  1.09861229 1.60943791 1.79175947
 0.71783979 1.09861229 0.91629073 0.95551145 1.64865863 0.44468582
 1.46787435 1.25561604 1.09861229 0.40546511 0.56531381 1.90657514
 1.16627094 0.69314718 0.68309684 1.32441896 0.97077892 1.14740245
 0.90421815 0.         0.69813472 0.73716407 0.67803354 1.09861229
 1.1442228  1.60943791 0.78845736 0.22314355 1.1249296  1.38629436
 1.09861229 0.99694863 1.09861229 1.22377543 0.60431597 1.60943791
 0.70803579 1.64287269 0.69314718 1.38629436 1.76644166 1.09861

# apply round, floor and ceil operation on tip array

In [51]:
# apply round, floor and ceil operation on tip array
print("Rounded tips:", np.round(tip_array, 2))
print("Floored tips:", np.floor(tip_array))
print("Ceiled tips:", np.ceil(tip_array))


Rounded tips: [ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2.    2.  

# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

In [52]:
# 1D array: indexing and slicing (5 examples)
arr1 = np.arange(1, 11)
print("1D index first:", arr1[0])
print("1D index last:", arr1[-1])
print("1D slice first 5:", arr1[:5])
print("1D slice every 2nd:", arr1[::2])
print("1D slice reverse:", arr1[::-1])

# 2D array: indexing and slicing (5 examples)
arr2 = np.arange(1, 13).reshape(3, 4)
print("\n2D element [0,1]:", arr2[0, 1])
print("2D first row:", arr2[0, :])
print("2D last column:", arr2[:, -1])
print("2D first 2 rows:", arr2[:2, :])
print("2D sub-array:", arr2[1:, 1:3])

# 3D array: indexing and slicing (5 examples)
arr3 = np.arange(1, 25).reshape(2, 3, 4)
print("\n3D element [0,1,2]:", arr3[0, 1, 2])
print("3D first block:", arr3[0])
print("3D first row of first block:", arr3[0, 0, :])
print("3D first column across rows:", arr3[:, :, 0])
print("3D sub-array:", arr3[:, 1:, 1:3])


1D index first: 1
1D index last: 10
1D slice first 5: [1 2 3 4 5]
1D slice every 2nd: [1 3 5 7 9]
1D slice reverse: [10  9  8  7  6  5  4  3  2  1]

2D element [0,1]: 2
2D first row: [1 2 3 4]
2D last column: [ 4  8 12]
2D first 2 rows: [[1 2 3 4]
 [5 6 7 8]]
2D sub-array: [[ 6  7]
 [10 11]]

3D element [0,1,2]: 7
3D first block: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3D first row of first block: [1 2 3 4]
3D first column across rows: [[ 1  5  9]
 [13 17 21]]
3D sub-array: [[[ 6  7]
  [10 11]]

 [[18 19]
  [22 23]]]


# stacking and spliting

In [70]:
d = np.arange(27).reshape(3,9)
e = np.arange(28,55).reshape(3,9)
print(d)
print(e)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]
[[28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]]


# use hstack() and vstack()

In [56]:
# use hstack() and vstack()
h_stacked = np.hstack((d, e))
v_stacked = np.vstack((d, e))

print("Horizontal stacking (hstack):\n", h_stacked)
print("\nVertical stacking (vstack):\n", v_stacked)


Horizontal stacking (hstack):
 [[ 0  1  2  3  4  5  6  7  8 28 29 30 31 32 33 34 35 36]
 [ 9 10 11 12 13 14 15 16 17 37 38 39 40 41 42 43 44 45]
 [18 19 20 21 22 23 24 25 26 46 47 48 49 50 51 52 53 54]]

Vertical stacking (vstack):
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]]


# use hsplit() and vsplit()

In [57]:
# use hsplit() and vsplit()
h_split = np.hsplit(d, 3)
v_split = np.vsplit(d, 3)

print("Horizontal split:")
for part in h_split:
    print(part)

print("\nVertical split:")
for part in v_split:
    print(part)


Horizontal split:
[[ 0  1  2]
 [ 9 10 11]
 [18 19 20]]
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]
[[ 6  7  8]
 [15 16 17]
 [24 25 26]]

Vertical split:
[[0 1 2 3 4 5 6 7 8]]
[[ 9 10 11 12 13 14 15 16 17]]
[[18 19 20 21 22 23 24 25 26]]
